### ISSUE TITLE
slider.py - AttributeError: type object 'Qt' has no attribute 'Orientations'

### ISSUE THREAD

**Issue by dabrown645** [janbodnar/PyQt6-Tutorial-Examples#1]
This is easily fixed by changing
        sld = QSlider(Qt.Orientations.Horizontal, self)
to
        sld = QSlider(Qt.Orientation.Horizontal, self)

**Comment by ChuanPoLee** [comment]
widgets2/splitter.py also has this problem. Remove last char 's' of Qt.Orientations
+
events/signal_slot.py
customwidget/burning_widget.py

**Comment by janbodnar** [comment]
What version of PyQt6 are you using? (Mine is 6.0.3) I remember that the names of the enums were changed
between the recent versions.

**Comment by dabrown645** [comment]
I am using 
PyQt6==6.1.1
  - PyQt6-Qt6 [required: >=6.1.1, installed: 6.1.2]
  - PyQt6-sip [required: >=13.1,<14, installed: 13.1.0]

**Comment by janbodnar** [comment]
OK, I will upgrade my libraries and fix this.

**Comment by janbodnar** [comment]
Corrected.
