### ISSUE TITLE
events/event_object.py AttributeError: type object 'Qt' has no attribute 'Alignment'

### ISSUE THREAD

**Issue by ChuanPoLee** [janbodnar/PyQt6-Tutorial-Examples#3]
change 
Qt.Alignment.AlignTop
to 
Qt.AlignmentFlag.AlignTop

**Comment by janbodnar** [comment]
What version of PyQt6 are you using? I have 6.0.3. We have to figure out which one is more recent.

**Comment by ChuanPoLee** [comment]
PyQt6 == 6.1.0
python 3.7, Debian 10.

**Comment by janbodnar** [comment]
Corrected.
